In [5]:
import numpy as np
# normal list
l = [1,2,3,'evans']
# array
np.array([1,2,3,'evans'])


array(['1', '2', '3', 'evans'], dtype='<U11')

In [6]:
type(np.array([1,2,3,'evans']))

numpy.ndarray

In [7]:
# upcasting
np.array([1,2,3.0])

array([1., 2., 3.])

In [8]:
# Two dimension
np.array([[1,2],[9,5]])

array([[1, 2],
       [9, 5]])

In [9]:
# minimum dimension
np.array([4,5], ndmin=3) # this is a three dimensional list

array([[[4, 5]]])

In [14]:
# dtype 
np.array([1,5, 'evans'], dtype=object, ndmin=4)

array([[[[1, 5, 'evans']]]], dtype=object)

In [17]:
np.array([[1,3], [6,5]], dtype=complex, ndmin=5 )

array([[[[[1.+0.j, 3.+0.j],
          [6.+0.j, 5.+0.j]]]]])

In [27]:
# datatype consisting more than element
a = np.array([(5,3), (8,4)], dtype=[('a', '<i2'), ('b', "<i4")])
a

array([(5, 3), (8, 4)], dtype=[('a', '<i2'), ('b', '<i4')])

In [28]:
a[0]

(5, 3)

In [29]:
a[0][1]

3

In [30]:
a[1][1]

4

In [32]:
type(a[0][1])

numpy.int32

In [37]:
a = np.array([(2,3), (6,7), (3,6), (7,8)], dtype=[('a', '<i8'), ('b', '<i4')])

In [38]:
a[3][1]

8

In [39]:
type(a[3][1])

numpy.int32

In [47]:
b = np.array([(3,4,5,6), (6,4,3,2)], dtype=[('a', '<i4'), ('b', '<i2'), ('c', '<i8'), ('d', '<i4')])
b

array([(3, 4, 5, 6), (6, 4, 3, 2)],
      dtype=[('a', '<i4'), ('b', '<i2'), ('c', '<i8'), ('d', '<i4')])

In [48]:
type(b[1][2])

numpy.int64

In [49]:
type(b)

numpy.ndarray

## matrix

In [51]:
np.mat(np.array([[5,7], [3,9]]))

matrix([[5, 7],
        [3, 9]])

In [59]:
# data which is in string to a string
np.mat('4 7; 3 7')

matrix([[4, 7],
        [3, 7]])