In [65]:
import pandas as pd
import numpy as np
# setting the random seed
np.random.seed(0)
# laoding the iris dataset
from sklearn.datasets import load_iris
# importing the random forest module
from sklearn.ensemble import RandomForestClassifier

In [66]:
# create an object called iris with iris data
iris = load_iris()
print("iris")

# creating a dataframe with four feature variables
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head(10)

iris


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [96]:
# adding another column for the species names
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
df[70:100]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
70                5.9               3.2                4.8               1.8   
71                6.1               2.8                4.0               1.3   
72                6.3               2.5                4.9               1.5   
73                6.1               2.8                4.7               1.2   
74                6.4               2.9                4.3               1.3   
75                6.6               3.0                4.4               1.4   
76                6.8               2.8                4.8               1.4   
77                6.7               3.0                5.0               1.7   
78                6.0               2.9                4.5               1.5   
79                5.7               2.6                3.5               1.0   
80                5.5               2.4                3.8               1.1   
81                5.5               2.4                3.7               1.0   
82                5.8               2.7                3.9               1.2   
83                6.0               2.7                5.1               1.6   
84                5.4               3.0                4.5               1.5   
85                6.0               3.4                4.5               1.6   
86                6.7               3.1                4.7               1.5   
87                6.3               2.3                4.4               1.3   
88                5.6               3.0                4.1               1.3   
89                5.5               2.5                4.0               1.3   
90                5.5               2.6                4.4               1.2   
91                6.1               3.0                4.6               1.4   
92                5.8               2.6                4.0               1.2   
93                5.0               2.3                3.3               1.0   
94                5.6               2.7                4.2               1.3   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

       species  is_train  
70  versicolor     False  
71  versicolor      True  
72  versicolor     False  
73  versicolor      True  
74  versicolor      True  
75  versicolor      True  
76  versicolor      True  
77  versicolor      True  
78  versicolor      True  
79  versicolor      True  
80  versicolor      True  
81  versicolor      True  
82  versicolor      True  
83  versicolor      True  
84  versicolor      True  
85  versicolor      True  
86  versicolor      True  
87  versicolor      True  
88  versicolor      True  
89  versicolor     False  
90  versicolor      True  
91  versicolor      True  
92  versicolor      True  
93  versicolor      True  
94  versicolor      True  
95  versicolor      True  
96  versicolor      True  
97  versicolor      True  
98  versicolor     False  
99  versicolor      True

In [68]:
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [69]:
# creating the testing and the training data
df['is_train'] = np.random.uniform(0, 1, len(df)) <= 0.75
df.head(6)


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True  
5  setosa      True

In [70]:
# creating the testing and the training variables
train, test = df[df["is_train"]==True] , df[df['is_train']==False]

# print the training data
print("The training data lenght is:: ",len(train))
print("The training data lenght is:: ",len(test))

The training data lenght is::  118
The training data lenght is::  32


In [71]:
# creating a list of column names
features = df.columns[:4]

In [72]:
# converting each species name into digits
y = pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

## Creating the model

In [73]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_jobs=2, random_state=2)

In [76]:
# fitting the model the data
clf.fit(train[features], y)

RandomForestClassifier(n_jobs=2, random_state=2)

In [77]:
# testing the trained model
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [82]:
# viewing the predicted probability for the first 10-20 observations
clf.predict_proba(test[features])[10:20]

array([[1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.62, 0.38],
       [0.  , 0.99, 0.01],
       [0.  , 0.86, 0.14],
       [0.  , 0.07, 0.93],
       [0.  , 0.35, 0.65],
       [0.  , 0.99, 0.01],
       [0.  , 0.99, 0.01]])

In [84]:
# mapping the names for the plants for each predicted plant class
pred = iris.target_names[clf.predict(test[features])]
pred[:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [85]:
# viewing the actual species for the first 5 observation
test['species'].head(5)

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [88]:
# creating a confusion matrix
pd.crosstab(test['species'], pred, rownames=['Actual_species'], colnames=['predicted species'])

predicted species  setosa  versicolor  virginica
Actual_species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [90]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test['species'], pred)

array([[13,  0,  0],
       [ 0,  5,  2],
       [ 0,  0, 12]], dtype=int64)

In [102]:
# doing the actual prediction on the data that we dont know which flowers 
preds = iris.target_names[clf.predict( [[5.1, 3.5, 1.4, 0.2], [70, 5.9, 3.2, 4.8]] )]

print(preds)

"""sepal length (cm)	sepal width (cm)	petal length (cm)	petal width (cm)
0	5.1	3.5	1.4	0.2
1	4.9	3.0	1.4	0.2
2	4.7	3.2	1.3	0.2
3	4.6	3.1	1.5	0.2
4	5.0	3.6	1.4	0.2"""

['setosa' 'virginica']


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


'sepal length (cm)\tsepal width (cm)\tpetal length (cm)\tpetal width (cm)\n0\t5.1\t3.5\t1.4\t0.2\n1\t4.9\t3.0\t1.4\t0.2\n2\t4.7\t3.2\t1.3\t0.2\n3\t4.6\t3.1\t1.5\t0.2\n4\t5.0\t3.6\t1.4\t0.2'