In [143]:
import pandas as pd
import numpy as np
from numpy.random import randn as rn
np.random.seed(100)

matrix_shape = rn(3,2)
matrix_shape

array([[-1.74976547,  0.3426804 ],
       [ 1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884]])

In [149]:
# testing if it is true that seed makes the random numbers not to change
np.random.seed(100)
matrix_shape = rn(3,2)
matrix_shape

array([[-1.74976547,  0.3426804 ],
       [ 1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884]])

In [27]:
column_names = ['col1', 'col2']
row_names = ['row1', 'row2', 'row3']
df = pd.DataFrame(matrix_shape, columns=column_names, index=row_names,)
df

col1      col2
row1 -1.749765  0.342680
row2  1.153036 -0.252436
row3  0.981321  0.514219

In [23]:
# extracting the whole column one

In [24]:
df['col1']

row1   -1.749765
row2    1.153036
row3    0.981321
Name: col1, dtype: float64

In [25]:
# extracting the cell (0,0)
df.iloc[0,0]

-1.7497654730546974

In [30]:
# extracting a whole rows
df.iloc[[0,1]]

col1      col2
row1 -1.749765  0.342680
row2  1.153036 -0.252436

In [34]:
# whole of row 1
df.iloc[[0]]

col1     col2
row1 -1.749765  0.34268

## example 2

In [117]:
import numpy as np
import pandas as pd
from numpy.random import randn as rn
np.random.seed(10)

In [130]:
matrix = rn(5,4)
matrix

array([[-2.01771865,  0.54054071, -1.44229888, -1.60885036],
       [-1.00656856, -0.25753362,  0.73050745, -1.69840149],
       [ 1.67407555,  1.1637237 , -0.13257359, -0.29024581],
       [-0.95353242,  0.58804059,  0.06880147,  1.4120643 ],
       [-0.68621561,  0.54794393, -0.03638254, -0.84701625]])

In [46]:
# creating a dataframe from the matrix
df = pd.DataFrame(matrix, columns=['w', 'x', 'y', 'z'], index=['a', 'b', 'c', 'd', 'e'])
df

w         x         y         z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549
c  0.004291 -0.174600  0.433026  1.203037
d -0.965066  1.028274  0.228630  0.445138
e -1.136602  0.135137  1.484537 -1.079805

In [55]:
# extracting sections of this dataframe
df.iloc[[2, 3]][['x', 'y']]

x         y
c -0.174600  0.433026
d  1.028274  0.228630

In [68]:
# extracting two columns
df[['y', 'z']]

y         z
a -1.545400 -0.008384
b  0.265512  0.108549
c  0.433026  1.203037
d  0.228630  0.445138
e  1.484537 -1.079805

In [66]:
df.iloc[3][['w', 'x']]

w   -0.965066
x    1.028274
Name: d, dtype: float64

## loc

In [70]:
df.loc['c']

w    0.004291
x   -0.174600
y    0.433026
z    1.203037
Name: c, dtype: float64

In [73]:
df.loc[['c','d']]

w         x         y         z
c  0.004291 -0.174600  0.433026  1.203037
d -0.965066  1.028274  0.228630  0.445138

In [76]:
df.loc[['a' ,'b']]

w         x         y         z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549

In [77]:
df

w         x         y         z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549
c  0.004291 -0.174600  0.433026  1.203037
d -0.965066  1.028274  0.228630  0.445138
e -1.136602  0.135137  1.484537 -1.079805

In [79]:
df.loc['d'][['y', 'z']]

y    0.228630
z    0.445138
Name: d, dtype: float64

In [81]:
df.loc[['b', 'e', 'c']][['x', 'z']]

x         z
b -0.720086  0.108549
e  0.135137 -1.079805
c -0.174600  1.203037

In [157]:
np.random.seed(3)
matrix1 = rn(5,4)
matrix1

array([[ 1.78862847,  0.43650985,  0.09649747, -1.8634927 ],
       [-0.2773882 , -0.35475898, -0.08274148, -0.62700068],
       [-0.04381817, -0.47721803, -1.31386475,  0.88462238],
       [ 0.88131804,  1.70957306,  0.05003364, -0.40467741],
       [-0.54535995, -1.54647732,  0.98236743, -1.10106763]])

In [166]:
df = pd.DataFrame(matrix1, index = ['a', 'b', 'c', 'd', 'e'])
df

0         1         2         3
a  1.788628  0.436510  0.096497 -1.863493
b -0.277388 -0.354759 -0.082741 -0.627001
c -0.043818 -0.477218 -1.313865  0.884622
d  0.881318  1.709573  0.050034 -0.404677
e -0.545360 -1.546477  0.982367 -1.101068

In [171]:
df.iloc[[0,-1], [0,-1]]

0         3
a  1.788628 -1.863493
e -0.545360 -1.101068

In [172]:
df.iloc[2][1]

-0.47721803035950267

In [177]:
np.random.seed(9)
matrix2 = rn(5,4)
df = pd.DataFrame(matrix2, columns=['w','x','y','z'], index=[12,23,34,56,56])
df

w         x         y         z
12  0.001109 -0.289544 -1.116066 -0.012883
23 -0.378361 -0.481135 -1.517331 -0.490872
34 -0.240681 -0.647947  0.635891  1.740117
56  0.296682  0.707504  1.822816  0.430769
56  1.542730 -0.900721 -0.137125  1.297579

In [213]:
df.loc[23:56, 'w':'y']

w         x         y
23 -0.378361 -0.481135 -1.517331
34 -0.240681 -0.647947  0.635891
56  0.296682  0.707504  1.822816
56  1.542730 -0.900721 -0.137125

In [214]:
df

w         x         y         z
12  0.001109 -0.289544 -1.116066 -0.012883
23 -0.378361 -0.481135 -1.517331 -0.490872
34 -0.240681 -0.647947  0.635891  1.740117
56  0.296682  0.707504  1.822816  0.430769
56  1.542730 -0.900721 -0.137125  1.297579

In [216]:
df.loc[34:12:-1, "z":"x":-1]

z         y         x
34  1.740117  0.635891 -0.647947
23 -0.490872 -1.517331 -0.481135
12 -0.012883 -1.116066 -0.289544

In [217]:
# creating a new column "b" which is a summation of column "x"+"y"
df["b"] = df['x'] + df["y"]

In [218]:
df

w         x         y         z         b
12  0.001109 -0.289544 -1.116066 -0.012883 -1.405610
23 -0.378361 -0.481135 -1.517331 -0.490872 -1.998467
34 -0.240681 -0.647947  0.635891  1.740117 -0.012056
56  0.296682  0.707504  1.822816  0.430769  2.530319
56  1.542730 -0.900721 -0.137125  1.297579 -1.037846

In [219]:
# overwritting the column
df['w'] = df['x']

In [220]:
df

w         x         y         z         b
12 -0.289544 -0.289544 -1.116066 -0.012883 -1.405610
23 -0.481135 -0.481135 -1.517331 -0.490872 -1.998467
34 -0.647947 -0.647947  0.635891  1.740117 -0.012056
56  0.707504  0.707504  1.822816  0.430769  2.530319
56 -0.900721 -0.900721 -0.137125  1.297579 -1.037846

In [222]:
# droping some column eg fropping column "Z"
df.drop("z")


KeyError: "['z'] not found in axis"

In [228]:
df.drop("z", axis=1, inplace=True)

KeyError: "['z'] not found in axis"

In [229]:
df

w         x         y         b
12 -0.289544 -0.289544 -1.116066 -1.405610
23 -0.481135 -0.481135 -1.517331 -1.998467
34 -0.647947 -0.647947  0.635891 -0.012056
56  0.707504  0.707504  1.822816  2.530319
56 -0.900721 -0.900721 -0.137125 -1.037846

In [231]:
df.drop([34], axis=0)

w         x         y         b
12 -0.289544 -0.289544 -1.116066 -1.405610
23 -0.481135 -0.481135 -1.517331 -1.998467
56  0.707504  0.707504  1.822816  2.530319
56 -0.900721 -0.900721 -0.137125 -1.037846

In [233]:
# no need to specify the axis since the default axis is set to zero
df.drop(56)

w         x         y         b
12 -0.289544 -0.289544 -1.116066 -1.405610
23 -0.481135 -0.481135 -1.517331 -1.998467
34 -0.647947 -0.647947  0.635891 -0.012056

# conditional filtering

In [235]:
df>0

w      x      y      b
12  False  False  False  False
23  False  False  False  False
34  False  False   True  False
56   True   True   True   True
56  False  False  False  False

In [236]:
df

w         x         y         b
12 -0.289544 -0.289544 -1.116066 -1.405610
23 -0.481135 -0.481135 -1.517331 -1.998467
34 -0.647947 -0.647947  0.635891 -0.012056
56  0.707504  0.707504  1.822816  2.530319
56 -0.900721 -0.900721 -0.137125 -1.037846

In [239]:
df[df>0]

w         x         y         b
12       NaN       NaN       NaN       NaN
23       NaN       NaN       NaN       NaN
34       NaN       NaN  0.635891       NaN
56  0.707504  0.707504  1.822816  2.530319
56       NaN       NaN       NaN       NaN

In [241]:
import numpy as np
import pandas as pd
from numpy.random import randn as rn

In [257]:
np.random.seed(43)
matrix_shape = rn(5,4)
df = pd.DataFrame(matrix_shape, columns=['W', 'X', 'Y', 'Z'], index=['a', 'b', 'c', 'd', 'e'])
df

W         X         Y         Z
a  0.257400 -0.908481 -0.378503 -0.534916
b  0.858073 -0.413010  0.498189  2.010199
c  1.262862 -0.439215 -0.346438  0.455320
d -1.668663 -0.862085  0.492911 -0.124313
e  1.935136 -0.618443 -1.046839 -0.889618

In [258]:
df[df>0]

W   X         Y         Z
a  0.257400 NaN       NaN       NaN
b  0.858073 NaN  0.498189  2.010199
c  1.262862 NaN       NaN  0.455320
d       NaN NaN  0.492911       NaN
e  1.935136 NaN       NaN       NaN

In [259]:
df.iloc

In [260]:
df.loc[['a', 'b', 'c']]

W         X         Y         Z
a  0.257400 -0.908481 -0.378503 -0.534916
b  0.858073 -0.413010  0.498189  2.010199
c  1.262862 -0.439215 -0.346438  0.455320

In [263]:
df[df.loc[['a', 'b', 'c']]>0]

W   X         Y         Z
a  0.257400 NaN       NaN       NaN
b  0.858073 NaN  0.498189  2.010199
c  1.262862 NaN       NaN  0.455320
d       NaN NaN       NaN       NaN
e       NaN NaN       NaN       NaN

In [271]:
matrix_data = np.matrix('22,66,140; 42,70,140; 30,62,125; 35,68,160; 25,62,152')
row_labels = ['A', 'B', 'C', 'D', 'E']
column_headers = ['Age', 'Height', 'Weight']
df1 = pd.DataFrame(matrix_data, columns=column_headers, index=row_labels)
df1

Age  Height  Weight
A   22      66     140
B   42      70     140
C   30      62     125
D   35      68     160
E   25      62     152

In [277]:
df1[df1['Height']<65]

Age  Height  Weight
C   30      62     125
E   25      62     152

In [279]:
# height less than 65 weight greater than 125 age is greater than 30
# h>65  w>125 age>30

In [288]:
result = df1[df1['Height']>65]
result

Age  Height  Weight
A   22      66     140
B   42      70     140
D   35      68     160

In [292]:
result = result[result['Weight']>125]
result

Age  Height  Weight
A   22      66     140
B   42      70     140
D   35      68     160

In [295]:
result = result[result['Age']>30]
result

Age  Height  Weight
B   42      70     140
D   35      68     160

In [296]:
df1

Age  Height  Weight
A   22      66     140
B   42      70     140
C   30      62     125
D   35      68     160
E   25      62     152

In [311]:
df1[(df1['Height']>65) & (df1['Weight']>125) & (df1['Age']>30)]

Age  Height  Weight
B   42      70     140
D   35      68     160

In [313]:
# resetting the named index
df1.reset_index()

index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     140
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152

In [314]:
df1.reset_index(drop=True)

Age  Height  Weight
0   22      66     140
1   42      70     140
2   30      62     125
3   35      68     160
4   25      62     152

In [320]:
# adding another column
df1['profession'] ='student@teacher@engineer@farmer@nurse'.split(sep='@')

In [323]:
df1

Age  Height  Weight profession
A   22      66     140    student
B   42      70     140    teacher
C   30      62     125   engineer
D   35      68     160     farmer
E   25      62     152      nurse

In [322]:
df1.set_index('profession')

Age  Height  Weight
profession                     
student      22      66     140
teacher      42      70     140
engineer     30      62     125
farmer       35      68     160
nurse        25      62     152

### multi level indexes

In [373]:
from numpy.random import randn as rn
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inner = [1, 2, 3, 1, 2, 3]

hier_index = list(zip(outside, inner))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [375]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [376]:
np.random.seed(5)
matrix_data = np.round(rn(6,3))
matrix_data

array([[ 0., -0.,  2.],
       [-0.,  0.,  2.],
       [-1., -1.,  0.],
       [-0., -1., -0.],
       [-0.,  1., -2.],
       [-1.,  1.,  2.]])

In [377]:
df2 = pd.DataFrame(matrix_data, index=hier_index, columns=['A', 'B', 'c'])
df2

A    B    c
G1 1  0.0 -0.0  2.0
   2 -0.0  0.0  2.0
   3 -1.0 -1.0  0.0
G2 1 -0.0 -1.0 -0.0
   2 -0.0  1.0 -2.0
   3 -1.0  1.0  2.0

In [382]:
df2.loc['G1'].loc[3,'c']

0.0

In [398]:
df2.loc['G2'].iloc[[1,2]][['B', 'c']]

B    c
2  1.0 -2.0
3  1.0  2.0