In [59]:
import pandas as pd
import numpy as np



In [60]:
# reading the dataset
df = pd.read_csv("C:\\Users\\charles\\Desktop\\Jupiter\\edureka\\Decision_tree\\loan_prediction\\Default_Fin.csv")
df.head(5)

Index  Employed  Bank Balance  Annual Salary  Defaulted?
0      1         1       8754.36      532339.56           0
1      2         0       9806.16      145273.56           0
2      3         1      12882.60      381205.68           0
3      4         1       6351.00      428453.88           0
4      5         1       9427.92      461562.00           0

In [61]:
# length of the dataset
print("length of the dataset::",len(df.index))
print("dataset shape:: ", df.shape)

length of the dataset:: 10000
dataset shape::  (10000, 5)


In [62]:
# data shape
df.describe()

Index      Employed  Bank Balance  Annual Salary    Defaulted?
count  10000.00000  10000.000000  10000.000000   10000.000000  10000.000000
mean    5000.50000      0.705600  10024.498524  402203.782224      0.033300
std     2886.89568      0.455795   5804.579486  160039.674988      0.179428
min        1.00000      0.000000      0.000000    9263.640000      0.000000
25%     2500.75000      0.000000   5780.790000  256085.520000      0.000000
50%     5000.50000      1.000000   9883.620000  414631.740000      0.000000
75%     7500.25000      1.000000  13995.660000  525692.760000      0.000000
max    10000.00000      1.000000  31851.840000  882650.760000      1.000000

In [63]:
df.isnull().sum()

Index            0
Employed         0
Bank Balance     0
Annual Salary    0
Defaulted?       0
dtype: int64

In [64]:
# split the data into training and testing
X = df.drop(['Defaulted?', 'Index'], axis=1).values
y = df['Defaulted?'].values
print(X)

[[1.0000000e+00 8.7543600e+03 5.3233956e+05]
 [0.0000000e+00 9.8061600e+03 1.4527356e+05]
 [1.0000000e+00 1.2882600e+04 3.8120568e+05]
 ...
 [1.0000000e+00 1.0144920e+04 7.0363392e+05]
 [1.0000000e+00 1.8828120e+04 4.4002932e+05]
 [0.0000000e+00 2.4110400e+03 2.0235540e+05]]


In [65]:
# spliting the data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [66]:
# creating the model
from sklearn.tree import DecisionTreeClassifier

In [67]:
# creating an instance of this model
clf_entropy = DecisionTreeClassifier(criterion= "entropy", random_state=100, max_depth=100, min_samples_leaf=5)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=100, min_samples_leaf=5,
                       random_state=100)

In [79]:
# predicting using the model
#Employed	Bank Balance	Annual Salary	Defaulted?
# 1	  8754.36	  532339.56
# 0	22463.28	216929.88	1

y_pred_en = clf_entropy.predict([[1, 45673.28, 29.88]])
if y_pred_en == 0:
    print("he wont pay")
else:
    print("He will pay")

He will pay


In [80]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred_en)
score

ValueError: Found input variables with inconsistent numbers of samples: [2000, 1]

In [81]:
from sklearn.metrics import classification_report
score = classification_report(y_test, y_pred_en)

ValueError: Found input variables with inconsistent numbers of samples: [2000, 1]